### ISSUE TITLE
Видимо что-то поменялось на сайте. Doesn't work, короче.

### ISSUE THREAD

**Issue by vffuunnyy** [skorpionikus/dynamic-photo-vk#2]
Вот такая штучка
```
Traceback (most recent call last):
  File "./rollphotos.py", line 78, in get_json
    return json.loads(response.split('<!json>')[1].split('<!>')[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./rollphotos.py", line 148, in <module>
    res = target.change_photo(photo, photo_id)
  File "./rollphotos.py", line 56, in change_photo
    'hash': self.get_hash(pid)}
  File "./rollphotos.py", line 49, in get_hash
    j = get_json(r.text)
  File "./rollphotos.py", line 80, in get_json
    raise Exception(response[:150])
Exception: {"payload":[0,["album537860523_0",5,0.000000,[{"id":"537860523_456239018","base":"https:\/\/sun9-31.userapi.com\/","commcount":0,"commshown":0,"commen.....................
```

**Comment by vffuunnyy** [comment]
Я починил. Если код нужен, пишите в лс: [vk.com/int.parse](vk)
